name: shade
version: 0.1.4
description:  A fast and flexible Microservice oriented HTTP server framework for dart.
homepage: https://github.com/adam-soph/shade
repository: https://github.com/adam-soph/shade
environment:
  sdk: '>=2.7.0 <3.0.0'
